### ISSUE TITLE
HACER LA PORRA DE BLACK DOT

### ISSUE THREAD

**Issue by JP-coder2000** [Black-Dot-2024/black-dot-wiki#1]
## Descripción 
Una porra que compita contra la de Aira y que muestre la esencia del departamento

## Tasks
- [ ] Crear la porra
- [ ] Exponer la porra
- [ ] Aprobar la porra
